development:
  cloud_name: dxabyj9nm
  api_key: "247722174574778"
  api_secret: BaQjspmGbIby1LLz5XW2Wvc9bZI
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dxabyj9nm
  api_key: "247722174574778"
  api_secret: BaQjspmGbIby1LLz5XW2Wvc9bZI
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dxabyj9nm
  api_key: "247722174574778"
  api_secret: BaQjspmGbIby1LLz5XW2Wvc9bZI
  enhance_image_tag: true
  static_image_support: false
