name_max_length: 50
email_max_length: 255
pass_min_length: 6
title_max_length: 150
password_reset_expired: 2

admin:
  per_page: 10
  break_time: 10
  block: block
  unblock: unblock
  mod: mod
  member: member
movie:
  iframe_height: 315
  iframe_width: 560
  showing_day: 3
  per_page: 5
  picture_size: 5
  picture_resize_high: 355
  picture_resize_width: 240

price_vnd: 60000
price_usd: 3
